# SEO Values
title: Russo.js
tagline: With Russo.js, it’s easy for you!
description: Russian Cyrillic transliteration library using ISO 9.
url: https://linuxfandudeguy.github.io/russo-docs/
logo: https://draculatheme.com/static/icons/pack-1/045-dracula.svg

# Google Analytics ID
google_analytics:

# GitHub Values
github:
  owner_name: Dracula
  owner_url: https://github.com/dracula
  repository_url: https://github.com/dracula/gh-pages

show_downloads: true
show_header: true
remote_theme: "dracula/gh-pages"

sass:
    style: compressed

plugins:
  - jekyll-seo-tag
