# SEO Values
title: Russo.js
tagline: With Russo.js, it’s easy for you!
description: Russian Cyrillic transliteration library using ISO 9.
url: https://linuxfandudeguy.github.io/russo-docs/
logo: ./assets/images/index.txt.png

# Google Analytics ID
google_analytics:

# GitHub Values
github:
  owner_name: linuxfandudeguy
  owner_url: https://github.com/linuxfandudeguy
  repository_url: https://github.com/linuxfandudeguy/durokotter

show_downloads: true
show_header: true
remote_theme: "dracula/gh-pages"

sass:
    style: compressed

plugins:
  - jekyll-seo-tag
